import ru.vershinin.homework2.Game;
import ru.vershinin.homework2.WrongLengthExeption;

import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(App.class);
    private static Scanner in = new Scanner(System.in);

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println("Welcome to Bulls and Cows game!");
        startNewGame();
    }

    public static void startNewGame() {

        Game game = Game.getNewGame();

        System.out.printf("I offered a %d-letter word, your guess?\n", game.getSecretWordLength());

        int attempCount = 10;

        log.info(game.getSecretWord());

        for (int i = 0; i < attempCount; i++ ) {
            String word = in.next();

            try {
                Game.AttempResult attempResult = game.attempt(word);

                if (attempResult.getResult()) {
                    System.out.println("You won!");
                    break;
                }
                else
                {
                    System.out.println("Bulls " + attempResult.getBulls());
                    System.out.println("Cows " + attempResult.getCows());
                }

            } catch (WrongLengthExeption wrongLengthExeption) {
                System.out.println("Bad length of the word!");
            }

            if (i == attempCount - 1)
                System.out.println("You lose!");
        }

        System.out.println("Wanna play again? Y/N");
        String answer = in.next();

        if ( answer.indexOf('Y') != -1 || answer.indexOf('y') != -1 ) {
            startNewGame();
        }
        else {
            System.out.println("Have a nice day!");
        }
    }
}
