/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.FileReader;
import java.io.BufferedReader;
import java.util.ArrayList;
import java.io.FileNotFoundException;
import java.io.IOException;

public class Main {

    public static void main(String[] args) {
        try {
            FileReader fileReader = new FileReader("dictionary.txt");
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            ArrayList<String> dict = new ArrayList();
            String line = null;
            while ((line = bufferedReader.readLine()) != null) {
                dict.add(line);
            }

            GameState game = new GameState(dict);
            game.startGame();

            bufferedReader.close();
        } catch (FileNotFoundException e) {
            System.out.println("Unable to read dictionary.txt");
        } catch (IOException e) {
            System.out.println("IOException");
        }
    }
}
