/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.io.InputStream;
import java.io.IOException;

public class Main {

    public static void main(String[] args) {
        try {
            InputStream in = Main.class.getResourceAsStream("dictionary.txt");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(in));

            ArrayList<String> dict = new ArrayList();
            String line = null;
            while ((line = bufferedReader.readLine()) != null) {
                dict.add(line);
            }

            GameState game = new GameState(dict);
            game.startGame();

            bufferedReader.close();
        } catch (IOException e) {
            System.out.println("Unable to read dictionary.txt");
        }
    }
}
