FROM gradle:jdk8 as builder
USER root
COPY . /home/gradle/bomberman
WORKDIR /home/gradle/bomberman/
RUN gradle :matchmaker:bootRepack

FROM openjdk:8-jre-slim
COPY --from=builder /home/gradle/bomberman/matchmaker/build/libs/matchmaker*.jar /bin/
EXPOSE 8080
CMD ["/bin/bash","-c", "java -jar /bin/matchmaker*.jar"]