FROM gradle:jdk8 as builder
USER root
COPY . /home/gradle/bomberman
WORKDIR /home/gradle/bomberman/
RUN gradle :frontend:build

FROM jetty:9.4.5-alpine
COPY --from=builder /home/gradle/bomberman/frontend/build/libs/*.war /var/lib/jetty/webapps/ROOT.war
EXPOSE 8080