FROM gradle:jdk8 as builder
USER root
COPY . /home/gradle/bomberman
WORKDIR /home/gradle/bomberman/
RUN gradle :gameservice:bootRepack

FROM openjdk:8-jre-slim
COPY --from=builder /home/gradle/bomberman/gameservice/build/libs/gameservice*.jar /bin/
EXPOSE 8090
CMD ["/bin/bash","-c", "java -jar /bin/gameservice*.jar"]